name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - name: Lab 1
      run: pwsh -c ./lab1.ps1
    - name: Lab 2
      run: pwsh -c ./lab2.ps1
    - name: Lab 3
      run: pwsh -c ./lab3.ps1
