name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.5'
    - name: Lab 1
      run: pwsh -c ./tests/lab1.ps1
    - name: Lab 2
      run: pwsh -c ./tests/lab2.ps1
    - name: Lab 3
      run: pwsh -c ./tests/lab3.ps1
    - name: All tests
      run: pwsh -c ./tests/all.ps1
    - name: Batch tests (Serial Logging)
      run: python3 ./batch_test.py all -w 1
    - name: Batch tests (Parallel Logging)
      run: python3 ./batch_test.py all
    - name: Batch tests (Serial No-logging)
      run: python3 ./batch_test.py all -w 1 -f ''
    - name: Batch tests (Parallel No-logging)
      run: python3 ./batch_test.py all -f ''
    - name: Batch results
      run: cat ./logs/*/result.log
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ./logs